name: Release

on:
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip tests during build'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  packages: write
  actions: read

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository_owner == github.actor
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set Up Ballerina
      uses: ballerina-platform/setup-ballerina@v1.1.0
      with:
        version: 2201.12.7

    - name: Set Git Configs
      run: |
        git config --global user.name ${{ github.actor }}
        git config --global user.email ${{ github.actor }}@users.noreply.github.com

    #- name: Extract version from gradle.properties
    #  id: project_version
    #  run: |
    #    VERSION=$(grep '^version=' gradle.properties | cut -d'=' -f2)
    #    echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

    #- name: Pre-release dependency version update
    #  run: |
    #    echo "Pre-release dependency version update"
    #    ./gradlew clean build ${{ inputs.skip_tests && '-x test' || '' }}

    #- name: Run vulnerability scan
    #  uses: aquasecurity/trivy-action@master
    #  with:
    #    scan-type: 'rootfs'
    #    scan-ref: '.'
    #    format: 'table'
    #    exit-code: '1'

    - name: Get Release Version
      id: release_version
      run: echo "VERSION=$((grep -w 'version' | cut -d= -f2) < gradle.properties | rev | cut --complement -d- -f1 | rev)" >> $GITHUB_ENV

    - name: Create release branch
      run: |
        echo "Version: ${VERSION}"
        git checkout -b release-${VERSION}

    - name: Run Gradle release
      run: ./gradlew release -Prelease.useAutomaticVersion=true --no-configuration-cache
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Find distribution artifacts
      id: artifacts
      run: |
        ZIP_FILE=$(find distribution/build/distributions -name "*.zip" | head -n 1)
        JAR_FILE=$(find components/api-server/target/bin -name "*.jar" | head -n 1)
        echo "ZIP_FILE=${ZIP_FILE}" >> $GITHUB_OUTPUT
        echo "JAR_FILE=${JAR_FILE}" >> $GITHUB_OUTPUT
    
    - name: GitHub Release and Release Sync PR
      env:
        GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
      run: |
        gh release create v$VERSION --title "API-SERVER-v$VERSION"
        gh pr create --base ${GITHUB_REF##*/} --title "[Automated] Sync ${GITHUB_REF##*/} after $VERSION release" --body "Sync ${GITHUB_REF##*/} after $VERSION release"
