name: Release

on:
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip tests during build'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  packages: write
  actions: read
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository_owner == github.actor
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Get Ballerina Version
      run: |
        BAL_VERSION=$(grep -w 'ballerinaDistributionVersion' gradle.properties | cut -d= -f2 | rev | cut --complement -d- -f1 | rev)
        if [ -z "$BAL_VERSION" ]; then
          BAL_VERSION="latest"
        fi
        echo "BAL_VERSION=$BAL_VERSION" >> $GITHUB_ENV
        echo "Ballerina Version: $BAL_VERSION"
  
    - name: Set Up Ballerina
      uses: ballerina-platform/setup-ballerina@v1.1.3
      with:
        version: ${{ env.BAL_VERSION }}

    - name: Set Git Configs
      run: |
        git config --global user.name ${{ github.actor }}
        git config --global user.email ${{ github.actor }}@users.noreply.github.com

    #- name: Extract version from gradle.properties
    #  id: project_version
    #  run: |
    #    VERSION=$(grep '^version=' gradle.properties | cut -d'=' -f2)
    #    echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

    #- name: Pre-release dependency version update
    #  run: |
    #    echo "Pre-release dependency version update"
    #    ./gradlew clean build ${{ inputs.skip_tests && '-x test' || '' }}

    #- name: Run vulnerability scan
    #  uses: aquasecurity/trivy-action@master
    #  with:
    #    scan-type: 'rootfs'
    #    scan-ref: '.'
    #    format: 'table'
    #    exit-code: '1'

    - name: Get Release Version
      id: release_version
      run: echo "VERSION=$((grep -w 'version' | cut -d= -f2) < gradle.properties | rev | cut --complement -d- -f1 | rev)" >> $GITHUB_ENV

    - name: Create release branch
      run: |
        echo "Version: ${VERSION}"
        git checkout -b release-${VERSION}

    - name: Run Gradle release
      run: ./gradlew release -Prelease.useAutomaticVersion=true --no-configuration-cache
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to GitHub Packages
      run: ./gradlew publish
      env:
        publishUser: ${{ github.actor }}
        publishPAT: ${{ secrets.GITHUB_TOKEN }}
    
    - name: GitHub Release and Release Sync PR
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create v$VERSION --title "API-SERVER-v$VERSION"
        gh pr create --base ${GITHUB_REF##*/} --title "[Automated] Sync ${GITHUB_REF##*/} after $VERSION release" --body "Sync ${GITHUB_REF##*/} after $VERSION release"
